### ISSUE TITLE
the server has asked for the client to provide credentials

### ISSUE THREAD

**Issue by xwinie** [kubernetes/kube-state-metrics#120]
kube-state-metrics ：2017-04-12T01:56:13.362556000Z F0412 01:56:13.361945       1 main.go:73] Failed to create client: ERROR communicating with apiserver: the server has asked for the client to provide credentials
2017-04-12T01:56:13.362761000Z goroutine 1 [running]:
2017-04-12T01:56:13.362917000Z k8s.io/kube-state-metrics/vendor/github.com/golang/glog.stacks(0x234fb00, 0x0, 0x0, 0x0)
2017-04-12T01:56:13.363052000Z 	/usr/local/google/home/pszczesniak/go/src/k8s.io/kube-state-metrics/vendor/github.com/golang/glog/glog.go:766 +0xb8
2017-04-12T01:56:13.363185000Z k8s.io/kube-state-metrics/vendor/github.com/golang/glog.(*loggingT).output(0x232f800, 0xc800000003, 0xc82028aa80, 0x2303db0, 0x7, 0x49, 0x0)
2017-04-12T01:56:13.363307000Z 	/usr/local/google/home/pszczesniak/go/src/k8s.io/kube-state-metrics/vendor/github.com/golang/glog/glog.go:717 +0x259
2017-04-12T01:56:13.363422000Z k8s.io/kube-state-metrics/vendor/github.com/golang/glog.(*loggingT).printf(0x232f800, 0xc800000003, 0x1a0e560, 0x1b, 0xc820555ec0, 0x1, 0x1)
2017-04-12T01:56:13.363540000Z 	/usr/local/google/home/pszczesniak/go/src/k8s.io/kube-state-metrics/vendor/github.com/golang/glog/glog.go:655 +0x1d4
2017-04-12T01:56:13.363669000Z k8s.io/kube-state-metrics/vendor/github.com/golang/glog.Fatalf(0x1a0e560, 0x1b, 0xc820555ec0, 0x1, 0x1)
2017-04-12T01:56:13.363784000Z 	/usr/local/google/home/pszczesniak/go/src/k8s.io/kube-state-metrics/vendor/github.com/golang/glog/glog.go:1145 +0x5d
2017-04-12T01:56:13.363903000Z main.main()
2017-04-12T01:56:13.364022000Z 	/usr/local/google/home/pszczesniak/go/src/k8s.io/kube-state-metrics/main.go:73 +0x271

yaml:
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-state-metrics-deployment
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-state-metrics
        version: "v0.3.0"
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
      - name: kube-state-metrics
        image: registry.cn-shenzhen.aliyuncs.com/kim-docker/kube-state-metrics:v0.3.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: "kubeconfig"
          mountPath: "/etc/kubernetes/"
          readOnly: true
        args:
          # - --in-cluster=true
          # - --apiserver=https://kubernetes.default.svc
          - --kubeconfig=/etc/kubernetes/kubeconfig
      volumes:
      - name: "kubeconfig"
        hostPath:
          path: "/etc/kubernetes/"

kubeconfig:

apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    certificate-authority: /etc/kubernetes/ssl/ca.crt
    server: https://10.254.0.1
users:
- name: kubelet
  user:
    client-certificate: /etc/kubernetes/ssl/node.crt
    client-key: /etc/kubernetes/ssl/node.key
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context

**Comment by andrewhowdencom** [comment]
Is this on 1.6?

**Comment by brancz** [comment]
@xwinie can you elaborate on the environment you are running kube-state-metrics in? If you run it inside of your Kubernetes cluster (which is recommended), then you don't need to specify any flags like `--kubeconfig` instead the authentication is done via the service account. Particularly in Kubernetes 1.6 you need to also make sure the `ServiceAccount` kube-state-metrics is run under has the required RBAC roles it needs. (documented in this repository under `kubernetes/`)
