### ISSUE TITLE
kube-state-metrics crashes with many resources, Objects listed error:

### ISSUE THREAD

**Issue by githubcdr** [kubernetes/kube-state-metrics#1920]
**What happened**:

kube-state-metrics /metrics endpoint returns HTTP/500 errors with a lot of resources

**What you expected to happen**:

working /metrics

**How to reproduce it (as minimally and precisely as possible)**:

version 2.7.0 installed via kube-prometheus-stack

```
I1201 13:20:04.021493       1 wrapper.go:78] Starting kube-state-metrics
I1201 13:20:04.022713       1 server.go:138] "Used resources" resources="cronjobs,daemonsets,deployments,namespaces,nodes,persistentvolumeclaims,pers
I1201 13:20:04.022766       1 types.go:184] "Using all namespaces"
I1201 13:20:04.022787       1 server.go:166] "Metric allow-denylisting" allowDenyStatus="Excluding the following lists that were on denylist: "
W1201 13:20:04.022824       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work
I1201 13:20:04.023481       1 server.go:311] "Tested communication with server"
I1201 13:20:04.127181       1 server.go:316] "Run with Kubernetes cluster version" major="1" minor="22" gitVersion="v1.22.6" gitTreeState="clean" git
I1201 13:20:04.127210       1 server.go:317] "Communication with server successful"
I1201 13:20:04.127444       1 server.go:263] "Started metrics server" metricsServerAddress=":8080"
I1201 13:20:04.127476       1 metrics_handler.go:97] "Autosharding disabled"
I1201 13:20:04.127487       1 server.go:252] "Started kube-state-metrics self metrics server" telemetryAddress=":8081"
I1201 13:20:04.127860       1 server.go:69] levelinfomsgListening onaddress:8080
I1201 13:20:04.127901       1 server.go:69] levelinfomsgTLS is disabled.http2falseaddress:8080
I1201 13:20:04.127960       1 server.go:69] levelinfomsgListening onaddress:8081
I1201 13:20:04.127967       1 server.go:69] levelinfomsgTLS is disabled.http2falseaddress:8081
I1201 13:20:04.128222       1 builder.go:257] "Active resources" activeStoreNames="cronjobs,daemonsets,deployments,namespaces,nodes,persistentvolumec
I1201 13:20:20.607906       1 trace.go:205] Trace[1859859164]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.25.4/tools/cache/reflector.g
Trace[1859859164]: ---"Objects listed" error:<nil> 12684ms (13:20:16.812)
Trace[1859859164]: ---"SyncWith done" 3692ms (13:20:20.607)
Trace[1859859164]: [16.479755931s] [16.479755931s] END
I1201 13:20:25.721176       1 trace.go:205] Trace[690855691]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.25.4/tools/cache/reflector.go
Trace[690855691]: ---"Objects listed" error:<nil> 20600ms (13:20:24.728)
Trace[690855691]: [21.592987813s] [21.592987813s] END
```

**Anything else we need to know?**:

I tried to narrow it down by removing targets, but no results

**Environment**:
- kube-state-metrics version: 2.7.0
- Kubernetes version (use `kubectl version`): 1.22.3
- Cloud provider or hardware configuration: AKS Azure
- Other info: 34 nodes cluster

**Comment by CatherineF-dev** [comment]
Hi @githubcdr, could you try v2.7.0 with k8s 1.25, or v1.9.7 with k8s 1.22?
Not sure whether it's related to k8s version. https://github.com/kubernetes/kube-state-metrics#compatibility-matrix

`v2.7.0 with k8s 1.25` worked for my testing cluster.

**Comment by CatherineF-dev** [comment]
Also, you can increase log level using `-v`.  https://github.com/kubernetes/kube-state-metrics/blob/master/docs/cli-arguments.md

**Comment by githubcdr** [comment]
Hi, with version v2.3.0 and -v=6 I got this output;

```
F1202 10:12:35.817254       1 main.go:155] Failed to create client: error while trying to communicate with apiserver: Get "https://10.0.0.1:443/versi
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
    /go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:1038 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x26abd80, 0x3, 0x0, 0xc00062b110, 0x0, {0x1dec6af, 0x1}, 0xc000125590, 0x0)
    /go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:987 +0x5fd
k8s.io/klog/v2.(*loggingT).printf(0x0, 0x1837c54, 0x0, {0x0, 0x0}, {0x18347e6, 0x1b}, {0xc000125590, 0x1, 0x1})
    /go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:753 +0x1c5
k8s.io/klog/v2.Fatalf(...)
    /go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:1532
main.main()
    /go/src/k8s.io/kube-state-metrics/main.go:155 +0xdfc

goroutine 36 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0xc0001a9200)
    /go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:1181 +0x6a
created by k8s.io/klog/v2.init.0
    /go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:420 +0xfb

goroutine 45 [chan receive]:
k8s.io/kube-state-metrics/v2/pkg/util/proc.StartReaper.func1()
    /go/src/k8s.io/kube-state-metrics/pkg/util/proc/reaper.go:40 +0x93
created by k8s.io/kube-state-metrics/v2/pkg/util/proc.StartReaper
    /go/src/k8s.io/kube-state-metrics/pkg/util/proc/reaper.go:35 +0x98

goroutine 21 [syscall]:
os/signal.signal_recv()
    /usr/local/go/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
    /usr/local/go/src/os/signal/signal.go:151 +0x2c
```

**Comment by CatherineF-dev** [comment]
1. Is version v2.3.0 running with k8s 1.23?
2. Could you try `-v=6` for v2.7.0 as well?

**Comment by mrueg** [comment]
Can you also provide the full command you're using to run kube-state-metrics? What are the resource request/limits for the deployment?
