### ISSUE TITLE
Panic when pods have an owner without controllers

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kube-state-metrics#239]
```
	owners := p.GetOwnerReferences()
	if len(owners) == 0 {
		addGauge(descPodOwner, 1, "<none>", "<none>", "<none>")
	} else {
		for _, owner := range owners {
			addGauge(descPodOwner, 1, owner.Kind, owner.Name, strconv.FormatBool(*owner.Controller))
		}
	}
```

panics when you have an `Owner` without `Controller`.  `Controller` is an optional field - anyone doing garbage collection (which is what owner is for) will be broken with this check.

```
I0823 14:33:36.780982       1 main.go:243] Starting metrics server: :8080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x122eb23]

goroutine 245 [running]:
k8s.io/kube-state-metrics/collectors.(*podCollector).collectPod(0xc42040dbe0, 0xc429e3acc0, 0x0, 0x0, 0x0, 0x0, 0xc428c28d40, 0xf, 0x0, 0x0, ...)
	/usr/local/google/home/loburm/go/src/k8s.io/kube-state-metrics/collectors/pod.go:279 +0x313
k8s.io/kube-state-metrics/collectors.(*podCollector).Collect(0xc42040dbe0, 0xc429e3acc0)
	/usr/local/google/home/loburm/go/src/k8s.io/kube-state-metrics/collectors/pod.go:214 +0x117
k8s.io/kube-state-metrics/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc427fae8d0, 0xc429e3acc0, 0x1d6dd60, 0xc42040dbe0)
	/usr/local/google/home/loburm/go/src/k8s.io/kube-state-metrics/vendor/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x61
created by k8s.io/kube-state-metrics/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/usr/local/google/home/loburm/go/src/k8s.io/kube-state-metrics/vendor/github.com/prometheus/client_golang/prometheus/registry.go:434 +0x27c
```

The Collector dereference should be guarded.

**Comment by brancz** [comment]
Absolutely. I'm surprised how this hasn't come up until now. We'll get the fix in and cut a release.

**Comment by smarterclayton** [comment]
I think a lot of people aren't using garbage collection owner references yet - we just happened to set a few of them by default on a very large cluster.

**Comment by andyxning** [comment]
As stated in [comment#190](https://github.com/kubernetes/kube-state-metrics/pull/190#issuecomment-319084632), i have found some materials about [`+optional` comment tag](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#optional-vs-required) . Unfortunatelly, no progress has been made for now.

I will speed it up.
