### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by r0fls** [kubernetes/kube-state-metrics#362]
I'm planning to look into this more later, but I'm seeing this error and the pod is in the CrashLoopBackOff state:

```
kubectl  logs -n prd354 shared-ksm-4065890672-zj9vd  -f
I0131 01:29:19.794874   11483 main.go:154] Using default collectors
I0131 01:29:19.795261   11483 main.go:202] service account token present: true
I0131 01:29:19.795281   11483 main.go:203] service host: https://10.3.0.1:443
I0131 01:29:19.796336   11483 main.go:229] Testing communication with server
I0131 01:29:19.807566   11483 main.go:234] Communication with server successful
I0131 01:29:19.808578   11483 main.go:279] Active collectors: daemonsets,jobs,replicationcontrollers,services,statefulsets,persistentvolumeclaims,deployments,limitranges,cronjobs,resourcequotas,nodes,pods,replicasets
I0131 01:29:19.808611   11483 main.go:243] Starting metrics server: :8080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11e0172]

goroutine 179 [running]:
time.time.Time.Unix(...)
        /usr/local/google/home/kawych/go-tools/src/k8s.io/kube-state-metrics/collectors/job.go:173
k8s.io/kube-state-metrics/collectors.(*jobCollector).collectJob(0xc42038c7a0, 0xc420058de0, 0x0, 0x0, 0x0, 0x0, 0xc4202f6760, 0xf, 0x0, 0x0, ...)
        /usr/local/google/home/kawych/go-tools/src/k8s.io/kube-state-metrics/collectors/job.go:173 +0x1f2
k8s.io/kube-state-metrics/collectors.(*jobCollector).Collect(0xc42038c7a0, 0xc420058de0)
        /usr/local/google/home/kawych/go-tools/src/k8s.io/kube-state-metrics/collectors/job.go:141 +0x12f
k8s.io/kube-state-metrics/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc420870830, 0xc420058de0, 0x1da0ea0, 0xc42038c7a0)
        /usr/local/google/home/kawych/go-tools/src/k8s.io/kube-state-metrics/vendor/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x61
created by k8s.io/kube-state-metrics/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /usr/local/google/home/kawych/go-tools/src/k8s.io/kube-state-metrics/vendor/github.com/prometheus/client_golang/prometheus/registry.go:431 +0x271
```

**Comment by r0fls** [comment]
This is on the `v1.0.1` version by the way.

**Comment by r0fls** [comment]
Looks like it's fixed in commit `69374b51`. Seems we should check here for nils too but maybe that's not needed: https://github.com/kubernetes/kube-state-metrics/blob/master/collectors/job.go#L207-L209

**Comment by andyxning** [comment]
@r0fls The type for `Status.Succeeded`, `Status.Failed` and `Status.Failed` is `int` instead of an pointer. There is no need to check there.

The panic is happens in https://github.com/kubernetes/kube-state-metrics/blob/v1.0.1/collectors/job.go#L173 which has been fixed in https://github.com/kubernetes/kube-state-metrics/commit/69374b51b008bd309f89a3949f546c8a011c6c19 which is in v1.1.0-rc0 and above releases. Please upgrade to a newer release.  :)

**Comment by andyxning** [comment]
Close this as this has been fixed in https://github.com/kubernetes/kube-state-metrics/commit/69374b51b008bd309f89a3949f546c8a011c6c19

**Comment by amigold** [comment]
I'm now getting this with version `1.8.0`

```
2019-10-28T21:24:42.675762815Z I1028 21:24:42.675238       1 main.go:86] Using default collectors
2019-10-28T21:24:42.675787159Z I1028 21:24:42.675327       1 main.go:98] Using all namespace
2019-10-28T21:24:42.675791742Z I1028 21:24:42.675354       1 main.go:139] metric white-blacklisting: blacklisting the following items: 
2019-10-28T21:24:42.675795146Z W1028 21:24:42.675444       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2019-10-28T21:24:42.689188685Z I1028 21:24:42.689017       1 main.go:184] Testing communication with server
2019-10-28T21:24:42.700660279Z I1028 21:24:42.699935       1 main.go:189] Running with Kubernetes cluster version: v1.9. git version: v1.9.6. git tree state: clean. commit: 9f8ebd171479bec0ada837d7ee641dec2f8c6dd1. platform: linux/amd64
2019-10-28T21:24:42.700676791Z I1028 21:24:42.699951       1 main.go:191] Communication with server successful
2019-10-28T21:24:42.700680717Z I1028 21:24:42.700075       1 main.go:225] Starting metrics server: 0.0.0.0:8080
2019-10-28T21:24:42.700683953Z I1028 21:24:42.700213       1 metrics_handler.go:96] Autosharding disabled
2019-10-28T21:24:42.701001208Z I1028 21:24:42.700751       1 builder.go:144] Active collectors: certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,namespaces,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses
2019-10-28T21:24:42.701351678Z I1028 21:24:42.701181       1 main.go:200] Starting kube-state-metrics self metrics server: 0.0.0.0:8081
2019-10-28T21:24:42.706465913Z E1028 21:24:42.706174       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
```

**Comment by tariq1890** [comment]
Are there any other error traces/details beyond what you have provided?

**Comment by tariq1890** [comment]
@amigold Can you check what all are the resource types you have in your cluster? This would help us narrow down where we might need to place a nil check.

This command should help you determine that info.

`kubectl api-resources --verbs=list -o name | xargs -n 1 kubectl get -o name`

**Comment by amigold** [comment]
I downgraded to an older version because my test cluster is a bit old. All good now. Thanks!
